image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - echo "Running the automated tests...."
            - mvn --version
            - mvn clean test
            - mvn allure:report
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
