image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
    - step:
        name: Build, Test And Generate Report
        caches:
          - maven
        script:
          - echo "Running the automated tests...."
          - mvn --version
          - mvn -q test
          - echo "Generating Allure report...."
          - mvn allure:report
        artifacts:
          - target/html-report/**