image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - echo "Running the automated tests...."
            - mvn --version
            - mvn clean test -Dselenide.headless=true
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
          artifacts:
            - ./**/test-results/**
      - step:
          name: Allure report
          script:
            - echo "Generating Allure report...."
            - mvn allure:report
            - pipe: atlassian/git-secrets-scan:0.4.3