image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - echo "Running the automated tests...."
          - mvn --version
          - mvn clean test
        artifacts:
          - target/**
          - build/**
    - step:
        name: Allure report
        script:
          - pwd
          - echo "Generating Allure report...."
          - mvn allure:report
        artifacts:
          - target/**