image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
    - step:
        name: Build, Test And Generate Report
        caches:
          - maven
        script:
          - echo "Running the automated tests...."
          - Xvfb :10 -ac &
          - export DISPLAY=:10
          - mvn --version
          - mvn -B verify
          - echo "Generating Allure report...."
          - mvn allure:report
        services:
          - chrome
        artifacts:
          - ./**/test-results/

definitions:
    services:
      chrome:
        image: selenium/standalone-chrome