image: maven:3.8.2-jdk-11

pipelines:
  default:
    - step:
        name: Build and Test And Generate Report
        caches:
          - maven
        script:
          - echo "Running the automated tests...."
          - mvn --version
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - mvn clean install
          - echo "Generating Allure report...."
          - mvn allure:report
        services:
          - docker
        artifacts:
          - ./**/opt/atlassian/pipelines/agent/build/target/site/